services:
  - type: web
    name: agri-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: index.js
    rootDir: backend
    envVars:
      - key: OPEN_API_KEY
        sync: false
